In [1]:
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
#from keras.utils.vis_utils import plot_model
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding
import numpy as np

In [2]:
data = """ Jack and Jill went up the hill\n
		To fetch a pail of water\n
		Jack fell down and broke his crown\n
		And Jill came tumbling after\n """
print(data)

 Jack and Jill went up the hill

		To fetch a pail of water

		Jack fell down and broke his crown

		And Jill came tumbling after
 


In [3]:
tokenizer = Tokenizer(lower=True)

tokenizer.fit_on_texts([data])
encoded = tokenizer.texts_to_sequences([data])[0]
print(encoded)

[2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21]


In [12]:
tokenizer.index_word.get(1)

'and'

In [13]:
vocab_size = len(tokenizer.word_index) + 1
vocab_size

22

In [15]:
sequences = list()
for i in range(1, len(encoded)):
	sequence = encoded[i-1:i+1]
	sequences.append(sequence)
print(sequences)

[[2, 1], [1, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10], [10, 11], [11, 12], [12, 13], [13, 2], [2, 14], [14, 15], [15, 1], [1, 16], [16, 17], [17, 18], [18, 1], [1, 3], [3, 19], [19, 20], [20, 21]]


In [16]:
sequences = array(sequences)
print(sequences)

[[ 2  1]
 [ 1  3]
 [ 3  4]
 [ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]
 [10 11]
 [11 12]
 [12 13]
 [13  2]
 [ 2 14]
 [14 15]
 [15  1]
 [ 1 16]
 [16 17]
 [17 18]
 [18  1]
 [ 1  3]
 [ 3 19]
 [19 20]
 [20 21]]


In [17]:
sequences.shape

(24, 2)

In [18]:
X, y = sequences[:,0],sequences[:,1]
print(X.shape)
print(y.shape)

(24,)
(24,)


In [21]:
X[1]

1

In [22]:
y[1]

3

In [23]:
y = to_categorical(y, num_classes=vocab_size)
print(y)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [27]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))
# compile network
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# summarize defined model
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 1, 10)             220       
                                                                 
 lstm_1 (LSTM)               (None, 50)                12200     
                                                                 
 dense_1 (Dense)             (None, 22)                1122      
                                                                 
Total params: 13542 (52.90 KB)
Trainable params: 13542 (52.90 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:

model.fit(X, y, epochs=500, verbose=2)


Epoch 1/500
1/1 - 2s - loss: 3.0903 - accuracy: 0.0000e+00 - 2s/epoch - 2s/step
Epoch 2/500
1/1 - 0s - loss: 3.0895 - accuracy: 0.0000e+00 - 9ms/epoch - 9ms/step
Epoch 3/500
1/1 - 0s - loss: 3.0887 - accuracy: 0.0833 - 7ms/epoch - 7ms/step
Epoch 4/500
1/1 - 0s - loss: 3.0879 - accuracy: 0.1250 - 7ms/epoch - 7ms/step
Epoch 5/500
1/1 - 0s - loss: 3.0871 - accuracy: 0.1250 - 6ms/epoch - 6ms/step
Epoch 6/500
1/1 - 0s - loss: 3.0863 - accuracy: 0.1250 - 7ms/epoch - 7ms/step
Epoch 7/500
1/1 - 0s - loss: 3.0855 - accuracy: 0.1250 - 7ms/epoch - 7ms/step
Epoch 8/500
1/1 - 0s - loss: 3.0846 - accuracy: 0.1250 - 7ms/epoch - 7ms/step
Epoch 9/500
1/1 - 0s - loss: 3.0838 - accuracy: 0.1250 - 8ms/epoch - 8ms/step
Epoch 10/500
1/1 - 0s - loss: 3.0829 - accuracy: 0.1250 - 7ms/epoch - 7ms/step
Epoch 11/500
1/1 - 0s - loss: 3.0821 - accuracy: 0.1250 - 8ms/epoch - 8ms/step
Epoch 12/500
1/1 - 0s - loss: 3.0812 - accuracy: 0.1250 - 6ms/epoch - 6ms/step
Epoch 13/500
1/1 - 0s - loss: 3.0803 - accuracy: 0.1250

In [36]:
tokenizer.word_index.items()

dict_items([('and', 1), ('jack', 2), ('jill', 3), ('went', 4), ('up', 5), ('the', 6), ('hill', 7), ('to', 8), ('fetch', 9), ('a', 10), ('pail', 11), ('of', 12), ('water', 13), ('fell', 14), ('down', 15), ('broke', 16), ('his', 17), ('crown', 18), ('came', 19), ('tumbling', 20), ('after', 21)])

In [38]:
def generate_seq(model, tokenizer, seed_text, n_words):
	in_text, result = seed_text, seed_text
	# generate a fixed number of words
	for _ in range(n_words):
		# encode the text as integer
		encoded = tokenizer.texts_to_sequences([in_text])[0]
		encoded = array(encoded)
		# predict a word in the vocabulary
		predicted_probabilities = model.predict(encoded)

		yhat = np.argmax(predicted_probabilities, axis=1)
		print('yhat',yhat)
		# map predicted word index to word
		out_word = ''
		for word, index in tokenizer.word_index.items():
			if index == yhat:
				out_word = word
				break
		# append to input
		in_text, result = out_word, result + ' ' + out_word
	return result

generate_seq(model, tokenizer, 'jack', 6)

[2]
1/1 [==============================] - 0s 29ms/step
yhat [1]
[1]
1/1 [==============================] - 0s 24ms/step
yhat [3]
[3]
1/1 [==============================] - 0s 26ms/step
yhat [4]
[4]
1/1 [==============================] - 0s 21ms/step
yhat [5]
[5]
1/1 [==============================] - 0s 20ms/step
yhat [6]
[6]
1/1 [==============================] - 0s 19ms/step
yhat [7]


'jack and jill went up the hill'